version: '3'
services:
  customercommandside:
    build: ../customers-service/
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:mysql://$DOCKER_HOST_IP/eventuate
      DB_DRIVERCLASSNAME: com.mysql.jdbc.Driver
      DB_USERNAME: mysqluser
      DB_PASSWORD: mysqlpw
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: $DOCKER_HOST_IP:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: $DOCKER_HOST_IP:2181
      JAVA_OPTS: -Xmx32m
